//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EventZone.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ActorAction
    {
        public ActorAction()
        {
            this.TrackingActions = new HashSet<TrackingAction>();
        }
    
        public int ActorActionID { get; set; }
        public string ActorName { get; set; }
    
        public virtual ICollection<TrackingAction> TrackingActions { get; set; }
    }
}
