//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EventZone.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Admin
    {
        public Admin()
        {
            this.TrackingActions = new HashSet<TrackingAction>();
            this.TrackingActions1 = new HashSet<TrackingAction>();
        }
    
        public long AdminID { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
        public Nullable<bool> RememberMe { get; set; }
        public bool IsBlocked { get; set; }
    
        public virtual ICollection<TrackingAction> TrackingActions { get; set; }
        public virtual ICollection<TrackingAction> TrackingActions1 { get; set; }
    }
}
