//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EventZoneC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Action
    {
        public Action()
        {
            this.TrackingUsers = new HashSet<TrackingUser>();
            this.TrackingAppeals = new HashSet<TrackingAppeal>();
            this.TrackingEvents = new HashSet<TrackingEvent>();
            this.TrackingReports = new HashSet<TrackingReport>();
        }
    
        public int ActionID { get; set; }
        public string ActionName { get; set; }
    
        public virtual ICollection<TrackingUser> TrackingUsers { get; set; }
        public virtual ICollection<TrackingAppeal> TrackingAppeals { get; set; }
        public virtual ICollection<TrackingEvent> TrackingEvents { get; set; }
        public virtual ICollection<TrackingReport> TrackingReports { get; set; }
    }
}
