//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EventZone.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Report
    {
        public Report()
        {
            this.TrackingReports = new HashSet<TrackingReport>();
        }
    
        public long ReportID { get; set; }
        public long EventID { get; set; }
        public long SenderID { get; set; }
        public string ReportType { get; set; }
        public string ReportContent { get; set; }
        public int ReportStatus { get; set; }
        public System.DateTime ReportDate { get; set; }
        public Nullable<System.DateTime> ResultDate { get; set; }
    
        public virtual Event Event { get; set; }
        public virtual User User { get; set; }
        public virtual ICollection<TrackingReport> TrackingReports { get; set; }
    }
}
